export const countries = [
  { image: require('./images/ar.png'), name: "Argentinia" }, 
  { image: require('./images/br.png'), name: "Brazil" }, 
  { image: require('./images/ca.png'), name: "Canada" }, 
  { image: require('./images/es.png'), name: "Spain" }, 
  { image: require('./images/mx.png'), name: "Mexico" }, 
  { image: require('./images/pt.png'), name: "Portugal" }, 
  { image: require('./images/tr.png'), name: "Turkey" }, 
  { image: require('./images/gr.png'), name: "Greece" }, 
  { image: require('./images/eg.png'), name: "Egypt" }, 
  { image: require('./images/au.png'), name: "Australia" }, 
  { image: require('./images/ci.png'), name: "Ivory Coast" }, 
  { image: require('./images/cm.png'), name: "Cameroon" }, 
  { image: require('./images/cy.png'), name: "Cyprus" }, 
  { image: require('./images/gh.png'), name: "Ghana" }, 
  { image: require('./images/jm.png'), name: "Jamaica" }, 
  { image: require('./images/jp.png'), name: "Japan" }, 
  { image: require('./images/kz.png'), name: "Kazachstan" }, 
  { image: require('./images/mt.png'), name: "Malta" }, 
  { image: require('./images/sy.png'), name: "Syria" }, 
  { image: require('./images/ch.png'), name: "Switzerland" } ];